name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    #strategy:
      #matrix:
        #node: [16,18,20]

    steps:
    - uses: actions/checkout@v4

    #- name: Setup Node | ${{matrix.node}}
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        #node-version: ${{matrix.node}}
        node-version: 18
        cache: 'npm'
    - run : npm i
    - run : npm run test

    - name: Generate docker tag # Definindo uma variável a partir do commit do github. Pegando os 7 caracteres iniciais do commit
      id: generate_tag
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Login into the container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build docker image
      run: docker build -t thixz/rocketseat-ci-api:${{steps.generate_tag.outputs.sha}} . # Recuperando a variável do step anterior

    - name: Push Image to docker
      run: docker push thixz/rocketseat-ci-api:${{steps.generate_tag.outputs.sha}}
